Repository mannygarcia98/habit-tracker, pull requests merged in 2022-07, with the labels that each got.

#22 added folder structure, new README
  README.md
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/src/utils/auth.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/config/connection.js
  server/models/index.js
  server/package.json
  server/schemas/index.js
  server/server.js
  server/utils/auth.js
  server/utils/dateFormat.js
Labels: good first issue

#24 Refactored and edited the README File, Also added a LICESNE
  LICENSE
  README.md
Labels: documentation

#27 Edited the .gitignore file and added the link to the code in the READ…
  .gitignore
  README.md
Labels: documentation

#29 Added the .env file to .gitignore file
  .gitignore
  package-lock.json
Labels: bug

#45 Feature/css
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/Calendar/index.css
  client/src/components/Calendar/index.js
  client/src/components/Footer/index.js
  client/src/components/Header/index.js
  client/src/images/jumbotron.jpg
  client/src/index.css
  client/src/index.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
Labels: enhancement

#48 Changed the favicon, as well as edited the button style and other CSS
  client/public/favicon.ico
  client/src/components/Calendar/index.js
  client/src/components/HabitForm/index.js
  client/src/components/Header/index.js
  client/src/index.css
  client/src/pages/Login.js
  client/src/pages/Signup.js
Labels: enhancement
